# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xci
# IP: The module: 'correlatorFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'correlatorFIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'correlatorFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xci
# IP: The module: 'correlatorFIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'correlatorFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'correlatorFIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
