@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jun 21 14:31:52 -0400 2023
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim uart_aggregate_test_behav -key {Behavioral:uart_aggregate_sim:Functional:uart_aggregate_test} -tclbatch uart_aggregate_test.tcl -view C:/Users/Christopher/Desktop/Research/full_dcs_system/full_dcs_system.srcs/uart_aggregate_sim/uart_aggregate_test_behav.wcfg -log simulate.log"
call xsim  uart_aggregate_test_behav -key {Behavioral:uart_aggregate_sim:Functional:uart_aggregate_test} -tclbatch uart_aggregate_test.tcl -view C:/Users/Christopher/Desktop/Research/full_dcs_system/full_dcs_system.srcs/uart_aggregate_sim/uart_aggregate_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
