# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlator_mt/correlator_mt.xci
# IP: The module: 'correlator_mt' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/ip/correlator_mt/ip/single_divider/single_divider.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==single_divider || ORIG_REF_NAME==single_divider} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/ip/correlator_mt/ip/int32_to_single/int32_to_single.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int32_to_single || ORIG_REF_NAME==int32_to_single} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlator_mt/correlator_mt.xci
# IP: The module: 'correlator_mt' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/ip/correlator_mt/ip/single_divider/single_divider.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==single_divider || ORIG_REF_NAME==single_divider} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/ip/correlator_mt/ip/int32_to_single/int32_to_single.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==int32_to_single || ORIG_REF_NAME==int32_to_single} -quiet] -quiet
