# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/design_1_DCS_Analyzer_0_0.xci
# IP: The module: 'design_1_DCS_Analyzer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/accum_single_float/accum_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accum_single_float || ORIG_REF_NAME==accum_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/multiply_single_float/multiply_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_single_float || ORIG_REF_NAME==multiply_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/subtract_single_float/subtract_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subtract_single_float || ORIG_REF_NAME==subtract_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/exponential_single_float/exponential_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exponential_single_float || ORIG_REF_NAME==exponential_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/sqrt_single_float/sqrt_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sqrt_single_float || ORIG_REF_NAME==sqrt_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/multiply_add_single_float/multiply_add_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_add_single_float || ORIG_REF_NAME==multiply_add_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/compare_less_than_float/compare_less_than_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==compare_less_than_float || ORIG_REF_NAME==compare_less_than_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/add_single_float/add_single_float.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_single_float || ORIG_REF_NAME==add_single_float} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/design_1_DCS_Analyzer_0_0.xci
# IP: The module: 'design_1_DCS_Analyzer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/accum_single_float/accum_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==accum_single_float || ORIG_REF_NAME==accum_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/multiply_single_float/multiply_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_single_float || ORIG_REF_NAME==multiply_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/subtract_single_float/subtract_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==subtract_single_float || ORIG_REF_NAME==subtract_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/exponential_single_float/exponential_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==exponential_single_float || ORIG_REF_NAME==exponential_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/sqrt_single_float/sqrt_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sqrt_single_float || ORIG_REF_NAME==sqrt_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/multiply_add_single_float/multiply_add_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply_add_single_float || ORIG_REF_NAME==multiply_add_single_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/compare_less_than_float/compare_less_than_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==compare_less_than_float || ORIG_REF_NAME==compare_less_than_float} -quiet] -quiet

# IP: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_DCS_Analyzer_0_0/sources_1/ip/add_single_float/add_single_float.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_single_float || ORIG_REF_NAME==add_single_float} -quiet] -quiet
