# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/bd/design_1/ip/design_1_uart_aggregator_0_0/design_1_uart_aggregator_0_0.xci
# IP: The module: 'design_1_uart_aggregator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_fifo || ORIG_REF_NAME==uart_fifo} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==correlatorFIFO || ORIG_REF_NAME==correlatorFIFO} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/intensityFIFO/intensityFIFO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intensityFIFO || ORIG_REF_NAME==intensityFIFO} -quiet] -quiet

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_uart_aggregator_0_0/design_1_uart_aggregator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_uart_aggregator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/bd/design_1/ip/design_1_uart_aggregator_0_0/design_1_uart_aggregator_0_0.xci
# IP: The module: 'design_1_uart_aggregator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/uart_fifo/uart_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_fifo || ORIG_REF_NAME==uart_fifo} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/correlatorFIFO/correlatorFIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==correlatorFIFO || ORIG_REF_NAME==correlatorFIFO} -quiet] -quiet

# IP: C:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.srcs/sources_1/ip/intensityFIFO/intensityFIFO.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==intensityFIFO || ORIG_REF_NAME==intensityFIFO} -quiet] -quiet

# XDC: c:/Users/johny/BOILresearch/full_dcs_system_6_23_23.xpr/full_dcs_system/full_dcs_system.gen/sources_1/bd/design_1/ip/design_1_uart_aggregator_0_0/design_1_uart_aggregator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_uart_aggregator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
